apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:6b458137de52d75162a637c7771b02168929d4560a645e1f33dab73bed93396f
  name: quay.io/hybridcloudpatterns/spring-petclinic:latest
  newName: quay-registry-quay-quay-enterprise.apps.lc-single-devsecops-34e2-1.blueprints.rhecoeng.com/devel/spring-petclinic
