apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:63d7d1c801b4f25e70bc5a79f74e1f551fa616561b2a46bc692a80e950c04063
  name: quay.io/hybridcloudpatterns/spring-petclinic:latest
  newName: quay-registry-quay-quay-enterprise.apps.lc-devsecops-20f1-1.blueprints.rhecoeng.com/devel/spring-petclinic
