apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:04a934e5eaefe0d2f4efbe3a0d82942a47fce75907ee4d9c1d5b8481aa0932cf
  name: quay.io/hybridcloudpatterns/spring-petclinic:latest
  newName: quay-registry-quay-quay-enterprise.apps.ocp-aws-hub.rhmulticloud-az.com/devel/spring-petclinic
