apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:20e989d01deb11b138acf8d30024cde001d6133f046276df1571ce4def61ffcb
  name: quay.io/hybridcloudpatterns/spring-petclinic:latest
  newName: quay-registry-quay-quay-enterprise.apps.lc-devsecops-20f1-1.blueprints.rhecoeng.com/devel/spring-petclinic
